### ISSUE TITLE
support for downloading subtitles?

### ISSUE THREAD

**Issue by ChocoTonic** [subramanya1997/download_echo360#2]

**Comment by subramanya1997** [comment]
@ChocoTonic as of now its available.

**Comment by ChocoTonic** [comment]
is there documentation on how to enable downloading of these subtitles?

**Comment by subramanya1997** [comment]
When I was building it i dint find any. It might have be updated now.

**Comment by ChocoTonic** [comment]
are you referring to your project being capable of downloading subtitles or the subtitles being exposed for downloading?

**Comment by subramanya1997** [comment]
subtitle being exposed.
